parse time in local tz
jfrog/terraform-provider-xray pull request #238
Opened 2024-09-09 19:14 UTC by ritzk

2024-09-09 19:17 UTC, ritzk commented
I have read the CLA Document and I hereby sign the CLA

2024-09-09 19:48 UTC, alexhung requested changes
Look ok. Please add a test for the tz use case in https://github.com/jfrog/terraform-provider-xray/blob/main/pkg/xray/resource/resource_xray_ignore_rule_test.go

2024-09-09 20:26 UTC, ritzk commented
> Look ok. Please add a test for the tz use case in https://github.com/jfrog/terraform-provider-xray/blob/main/pkg/xray/resource/resource_xray_ignore_rule_test.go

@alexhung  not familiar enough with go to write a test case for this usecase.

2024-09-10 16:08 UTC, alexhung commented
@ritzk Ok no problem. I'll add that once this is merged.

2024-09-10 16:10 UTC, alexhung approved these changes

2024-09-10 21:41 UTC, merged