Add subcategory in docs
jfrog/terraform-provider-xray pull request #44
Opened 2022-04-29 23:13 UTC by danielmkn

Subcategory organizes documents in the Terraform Registry UI

2022-04-30 05:41 UTC, chb0github approved these changes

2022-05-02 16:23 UTC, alexhung requested changes
LGTM except the missing closing parenthesis

2022-05-02 16:23 UTC, alexhung commented on docs/resources/license_policy.md
> +Please note: It's only compatible with Bearer token auth method (Identity and Access => Access Tokens.
Missing a closing parenthesis.

2022-05-02 16:23 UTC, alexhung commented on docs/resources/security_policy.md
> +Please note: It's only compatible with Bearer token auth method (Identity and Access => Access Tokens.
Same here

2022-05-02 16:27 UTC, danielmkn commented on docs/resources/license_policy.md
> +Please note: It's only compatible with Bearer token auth method (Identity and Access => Access Tokens.
thanks! Fixed!

2022-05-02 16:27 UTC, danielmkn commented on docs/resources/security_policy.md
> +Please note: It's only compatible with Bearer token auth method (Identity and Access => Access Tokens.
thanks! Fixed!

2022-05-02 16:39 UTC, alexhung approved these changes

2022-05-02 16:42 UTC, maheshjfrog approved these changes

2022-05-02 16:50 UTC, merged