Added contribution guide and simplified the readme to just have quick…
jfrog/terraform-provider-xray pull request #83
Opened 2022-10-28 21:48 UTC by Turhsus

…start instructions.

Reduced size of readme.

2022-10-28 22:01 UTC, danielmkn submitted a review, later dismissed

2022-10-31 16:15 UTC, alexhung requested changes

2022-10-31 16:15 UTC, alexhung commented on CONTRIBUTIONS.md
> +- [Go](https://golang.org/doc/install) 1.15+ (to build the provider plugin)
We've moved to Go 1.18 for a few months now.

2022-10-31 19:11 UTC, alexhung submitted a review, later dismissed

2022-10-31 19:51 UTC, alexhung approved these changes

2022-11-01 00:03 UTC, merged